sudo: required
services:
  - docker

before_install:
  - docker build -t faizananwer/react-test -f ./client/Dockerfile.dev ./client

  script:
    - docker run faizananwer/react-test npm test -- --coverage

  after_success:
    - docker build -t faizananwer/multi-client ./client
    - docker build -t faizananwer/multi-nginx ./nginx
    - docker build -t faizananwer/multi-server ./server
    - docker build -t faizananwer/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push faizananwer/multi-client
  - docker push faizananwer/multi-nginx
  - docker push faizananwer/multi-server
  - docker push faizananwer/multi-worker
